# ================= GLOBAL VARIABLES =================
variables:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: "900111020000"

  SONAR_PROJECT_KEY: "cash_bd_ada-ppi"

  ECS_CLUSTER_UAT: "cash_bd_ada-ppi"
  ECS_CLUSTER_PROD: "cash_bd_ada-ppi"

  ECR_REPO_UAT: "cash_bd_ada-ppi-uat"
  ECR_REPO_PROD: "cash_bd_ada-ppi-prod"

  ECS_SERVICE_UAT: "cash_bd_ada-ppi-uat"
  ECS_SERVICE_PROD: "cash_bd_ada-ppi-prod"

  TASK_DEF_UAT: "cash_bd_ada-ppi-uat"
  TASK_DEF_PROD: "cash_bd_ada-ppi-prod"

  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

# ================= STAGES =================
stages:
  - release
  - quality
  - build
  - security
  - push
  - deploy

# ================= TAG RELEASE =================
uat_tag_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  script:
    - export COMMIT_TAG="uat-$CI_COMMIT_SHORT_SHA"
    - release-cli create --name "Release $COMMIT_TAG" --tag-name $COMMIT_TAG
  tags: [verygudfl-linux]

prod_tag_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  script:
    - export COMMIT_TAG="prod-$CI_COMMIT_SHORT_SHA"
    - release-cli create --name "Release $COMMIT_TAG" --tag-name $COMMIT_TAG
  tags: [verygudfl-linux]

# ================= SONAR =================
sonar_scan:
  stage: quality
  tags: [verygudfl-linux]
  script:
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(uat|release)/'
  allow_failure: false

# ================= BUILD IMAGE (ONCE) =================
docker_build:
  stage: build
  image: docker:24
  services: [docker:24-dind]
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t app:$IMAGE_TAG .
    - docker save app:$IMAGE_TAG > image.tar
  artifacts:
    paths: [image.tar]
    expire_in: 1 day

# ================= TRIVY SECURITY SCAN =================
trivy_scan:
  stage: security
  image: aquasec/trivy
  needs: ["docker_build"]
  script:
    - docker load < image.tar
    - trivy image --severity CRITICAL,HIGH --exit-code 1 app:$IMAGE_TAG
  allow_failure: false

# ================= PUSH TO ECR UAT =================
push_ecr_uat:
  stage: push
  needs: ["docker_build"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  image: docker:24
  services: [docker:24-dind]
  script:
    - docker load < image.tar
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker tag app:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_UAT:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_UAT:$IMAGE_TAG

# ================= PUSH TO ECR PROD =================
push_ecr_prod:
  stage: push
  needs: ["docker_build"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  image: docker:24
  services: [docker:24-dind]
  script:
    - docker load < image.tar
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker tag app:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PROD:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PROD:$IMAGE_TAG

# ================= DEPLOY UAT =================
deploy_uat:
  stage: deploy
  needs: ["push_ecr_uat"]
  environment: uat
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER_UAT \
        --service $ECS_SERVICE_UAT \
        --force-new-deployment

# ================= DEPLOY PROD (MANUAL) =================
deploy_prod:
  stage: deploy
  environment:
    name: prod
    deployment_tier: production
  when: manual
  needs: ["push_ecr_prod"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER_PROD \
        --service $ECS_SERVICE_PROD \
        --force-new-deployment