# ================= GLOBAL VARIABLES =================
variables:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: "900111020000"

  PROJECT_NAME: "cash_bd_ada-ppi"
  ECR_REPO_UAT: "cash_bd_ada-ppi-uat"
  ECR_REPO_PROD: "cash_bd_ada-ppi-prod"

  ECS_CLUSTER_UAT: "cash_bd_ada-ppi"
  ECS_CLUSTER_PROD: "cash_bd_ada-ppi"

  ECS_SERVICE_UAT: "cash_bd_ada-ppi-uat"
  ECS_SERVICE_PROD: "cash_bd_ada-ppi-prod"

  TASK_DEF_UAT: "cash_bd_ada-ppi-uat"
  TASK_DEF_PROD: "cash_bd_ada-ppi-prod"

  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

# ================= STAGES =================
stages:
  - test
  - sonar
  - build
  - security
  - push
  - deploy-uat
  - deploy-prod

# ================= CODE QUALITY =================
sonar_scan:
  stage: sonar
  image: sonarsource/sonar-scanner-cli
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(uat|release)/'
  script:
    - sonar-scanner
  allow_failure: false

# ================= BUILD DOCKER IMAGE =================
docker_build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $PROJECT_NAME:$IMAGE_TAG .
    - docker save $PROJECT_NAME:$IMAGE_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day

# ================= TRIVY SECURITY SCAN =================
trivy_scan:
  stage: security
  image: aquasec/trivy
  needs: ["docker_build"]
  script:
    - docker load < image.tar
    - trivy image --severity CRITICAL,HIGH --exit-code 1 $PROJECT_NAME:$IMAGE_TAG
  allow_failure: false

# ================= PUSH TO AWS ECR =================
push_ecr_uat:
  stage: push
  needs: ["docker_build"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  image: docker:24
  services:
    - docker:dind
  script:
    - docker load < image.tar
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker tag $PROJECT_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_UAT:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_UAT:$IMAGE_TAG

push_ecr_prod:
  stage: push
  needs: ["docker_build"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  image: docker:24
  services:
    - docker:dind
  script:
    - docker load < image.tar
    - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker tag $PROJECT_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PROD:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PROD:$IMAGE_TAG

# ================= DEPLOY TO ECS UAT =================
deploy_uat:
  stage: deploy-uat
  environment: uat
  needs: ["push_ecr_uat"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  script:
    - IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_UAT:$IMAGE_TAG"
    - aws ecs update-service --cluster $ECS_CLUSTER_UAT \
        --service $ECS_SERVICE_UAT \
        --force-new-deployment \
        --task-definition $TASK_DEF_UAT

# ================= DEPLOY TO ECS PROD (MANUAL APPROVAL) =================
deploy_prod:
  stage: deploy-prod
  environment:
    name: prod
    url: https://prod.company.com
  when: manual
  needs: ["push_ecr_prod"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  script:
    - IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_PROD:$IMAGE_TAG"
    - aws ecs update-service --cluster $ECS_CLUSTER_PROD \
        --service $ECS_SERVICE_PROD \
        --force-new-deployment \
        --task-definition $TASK_DEF_PROD